// cloudflare/worker.ts
// Custom worker wrapper forwarding fetch requests to OpenNext and handling scheduled Cron Triggers.

// @ts-ignore: .open-next/worker.js is generated during opennextjs-cloudflare build
import openNextWorker from "../.open-next/worker.js";
// @ts-ignore: re-export all Durable Objects and classes generated by OpenNext
export * from "../.open-next/worker.js";

export interface Env {
  CRON_SECRET?: string;
  NEXT_INC_CACHE_R2_BUCKET?: any;
  ASSETS?: any;
  [key: string]: unknown;
}

export interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

export interface ScheduledController {
  scheduledTime: number;
  cron: string;
  noRetry(): void;
}

// Maps exact cron expressions from vercel.json to their endpoint paths
const CRON_ROUTES: Record<string, string> = {
  "0 0 * * *": "/api/newsletter/send-scheduled",
  "0 4 * * *": "/api/cron/update-rbi-rates",
  "0 9 */3 * *": "/api/cron/ping-secondary",
  "0 5 * * *": "/api/cron/sync-views",
};

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    return openNextWorker.fetch(request, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    const cron = controller.cron;
    const path = CRON_ROUTES[cron];
    const scheduledTime = new Date(controller.scheduledTime).toISOString();
    console.log(`[Cron Trigger] Invoked '${cron}' -> target '${path ?? 'unknown'}' at ${scheduledTime}`);

    if (!path) {
      console.warn(`[Cron Trigger] No route configured for cron schedule: '${cron}'`);
      return;
    }

    // Host that does NOT redirect: https://www.corplawupdates.in (apex redirects to www)
    const host = "https://www.corplawupdates.in";
    const targetUrl = `${host}${path}`;

    const headers: Record<string, string> = {
      "User-Agent": "Cloudflare-Worker-Cron/1.0",
      "host": "www.corplawupdates.in",
      "x-forwarded-host": "www.corplawupdates.in",
      "x-forwarded-proto": "https",
    };
    if (env.CRON_SECRET) {
      headers["Authorization"] = `Bearer ${env.CRON_SECRET}`;
    }

    const req = new Request(targetUrl, {
      method: "GET",
      headers,
    });

    let res = await openNextWorker.fetch(req, env, ctx);

    // If redirected (301, 302, 307, 308), log and follow redirect
    if ([301, 302, 307, 308].includes(res.status)) {
      const redirectLocation = res.headers.get("location");
      console.log(`[Cron Redirect] Route '${path}' returned HTTP ${res.status} redirecting to '${redirectLocation}'`);
      if (redirectLocation) {
        const nextUrl = redirectLocation.startsWith("http") ? redirectLocation : `${host}${redirectLocation}`;
        const nextReq = new Request(nextUrl, {
          method: "GET",
          headers,
        });
        res = await openNextWorker.fetch(nextReq, env, ctx);
      }
    }

    if (!res.ok) {
      const errorBody = await res.text();
      const errorMsg = `[Cron Failure] Route '${path}' failed with status ${res.status}: ${errorBody}`;
      console.error(errorMsg);
      throw new Error(errorMsg);
    }

    const successBody = await res.text();
    console.log(`[Cron Success] Route '${path}' executed successfully (status ${res.status}): ${successBody.slice(0, 300)}`);
  },
};
