'use client'

import React, { useState } from 'react'

const faqs = [
  {
    q: 'What is the fee for filing AOC-4 and MGT-7?',
    a: 'The normal filing fee for AOC-4 and MGT-7 depends on your company\'s authorized share capital (ranging from ₹200 to ₹600 for standard companies). However, if filed late, an uncapped penalty of ₹100 per day applies from the due date until the actual date of filing.'
  },
  {
    q: 'What is the fee for DIR-3 KYC?',
    a: 'DIR-3 KYC is completely free if filed before the due date (usually 30th September each year). If filed after the due date, a flat penalty of ₹5,000 is applicable regardless of the delay period.'
  },
  {
    q: 'Do OPC and Small Companies pay lower MCA fees?',
    a: 'Yes, One Person Companies (OPC) and Small Companies have a concessional fee structure. Their normal filing fees start from ₹50 and cap at ₹200, which is significantly lower than standard private or public limited companies.'
  },
  {
    q: 'How is the late filing penalty calculated for general forms like ADT-1 or INC-22?',
    a: 'For general forms, the late fee is a multiplier of the normal fee based on the period of delay. It starts at 1x or 2x for minor delays and can go up to 12x the normal fee for delays exceeding 180 days.'
  },
  {
    q: 'What happens if I don\'t file annual returns?',
    a: 'Non-filing of AOC-4 and MGT-7 for consecutive years can lead to the company being marked as "Active-non-compliant". Prolonged default may result in the Registrar striking off the company from ROC records, and the directors may face disqualification under Section 164 of the Companies Act.'
  },
  {
    q: 'Is stamp duty included in the MCA fees calculated here?',
    a: 'No, stamp duty is a state subject and is payable separately from MCA filing fees. Our calculator provides an indicative stamp duty estimate for Share Capital increase (SH-7) based on state-wise rates, but the exact amount is generated by the MCA portal during filing.'
  },
  {
    q: 'Can I get a waiver on MCA late filing fees?',
    a: 'Generally, the MCA does not provide waivers or refunds on late filing fees. Relief is only granted during special amnesty schemes announced by the government, such as the Company Fresh Start Scheme (CFSS).'
  }
]

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <div className="mb-20">
      <h2 className="text-2xl md:text-3xl font-bold text-navy dark:text-white font-heading mb-8">
        Frequently Asked Questions
      </h2>

      <div className="space-y-3">
        {faqs.map((faq, index) => {
          const isOpen = openIndex === index
          return (
            <div 
              key={index} 
              className={`border rounded-2xl overflow-hidden transition-all duration-200 ${
                isOpen 
                ? 'border-navy dark:border-slate-600 bg-slate-50 dark:bg-slate-800/50' 
                : 'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hover:border-slate-300 dark:hover:border-slate-700'
              }`}
            >
              <button
                className="w-full text-left px-6 py-5 flex items-center justify-between gap-4 focus:outline-none"
                onClick={() => toggle(index)}
                aria-expanded={isOpen}
              >
                <span className={`font-semibold text-lg ${isOpen ? 'text-navy dark:text-white' : 'text-slate-800 dark:text-slate-200'}`}>
                  {faq.q}
                </span>
                <span className={`shrink-0 transition-transform duration-200 ${isOpen ? 'rotate-180 text-navy dark:text-white' : 'text-slate-400'}`}>
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="6 9 12 15 18 9"></polyline>
                  </svg>
                </span>
              </button>
              
              <div 
                className={`px-6 overflow-hidden transition-all duration-200 ease-in-out ${
                  isOpen ? 'max-h-96 pb-6 opacity-100' : 'max-h-0 opacity-0'
                }`}
              >
                <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-[15px]">
                  {faq.a}
                </p>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
